version: "3.7"
services:

  minio:
    image: minio/minio # Stable minio
    volumes:
      - minio-data:/data
    networks:
      - xain-fl
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    expose:
      - "9000"

  redis:
    image: redis:5 # current stable version, v6 out between March 2020 and May 2020
    hostname: redis
    entrypoint: /usr/local/bin/redis-server --appendonly yes --appendfsync everysec # using combination of RDB and AOF for persistence: https://redis.io/topics/persistence
    volumes:
      - redis-data:/data
    networks:
      - xain-fl
    expose:
      - "6379"

  influxdb:
    image: influxdb:1.7 # current stable version, v2 is in Beta
    hostname: influxdb
    volumes:
      - influxdb-data:/var/lib/influxdb
    networks:
      - xain-fl
    expose:
      - "8086"

  xain-fl:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - xain-fl
    ports:
    - "50051:50051"

volumes:
  minio-data:
  redis-data:
  influxdb-data:

networks:
  xain-fl:
