version: "3.7"
services:

  minio:
    image: minio/minio # Stable minio
    volumes:
      - minio-data:/data
    networks:
      - xain-fl
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    expose:
      - "9000"

  xain-fl:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - xain-fl
    ports:
    - "50051:50051"

volumes:
  minio-data:

networks:
  xain-fl:
