openapi: 3.0.1
info:
  title: XAIN FL Aggregator API
  contact:
    email: engineering@xain.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 0.7.0
externalDocs:
  description: Find out more about XAIN FL
  url: https://docs.xain.io/
servers:
  - url: http://localhost:8082/
tags:
  - name: Aggregator
    description: API of the aggregator service
paths:
  /{client_id}/{client_token}:
    get:
      tags:
        - Aggregator
      parameters:
        - name: client_id
          in: path
          description: ID of the client
          required: true
          schema:
            $ref: "#/components/schemas/ClientID"
        - name: client_token
          in: path
          description: API token of the client
          required: true
          schema:
            $ref: "#/components/schemas/ClientToken"
      responses:
        200:
          description: weights of the global model
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
        404:
          description: client unknown
          content: {}
    post:
      tags:
        - Aggregator
      parameters:
        - name: client_id
          in: path
          description: ID of the client
          required: true
          schema:
            $ref: "#/components/schemas/ClientID"
        - name: client_token
          in: path
          description: API token of the client
          required: true
          schema:
            $ref: "#/components/schemas/ClientToken"
      requestBody:
        description: weights of the local model
        content:
          application/octet-stream:
            schema:
              type: string
              format: binary
      responses:
        200:
          description: successful operation
          content: {}
        404:
          description: client unknown
          content: {}
components:
  schemas:
    ClientID:
      description: client ID
      type: string
      format: uuid
      example: 1fa2f908-83e2-4f92-80e1-4baee0bf25a5
    ClientToken:
      description: client API token
      type: string
      format: uuid
      example: 2e8700a6-390d-411f-977b-9aa3bebc13e9
