openapi: 3.0.1
info:
  title: XAIN FL Aggregator API
  description: ""
  contact:
    email: engineering@xain.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
externalDocs:
  description: Find out more about XAIN FL
  url: https://docs.xain.io/
servers:
  - url: http://localhost:8082/
tags:
  - name: Aggregator
    description: Aggregator API
paths:
  /{client_id}/{client_token}:
    get:
      tags:
        - Aggregator
      parameters:
        - name: client_id
          in: path
          description: ID of the client
          required: true
          schema:
            type: string
        - name: client_token
          in: path
          description: Aggregator token of the client
          required: true
          schema:
            type: string
      responses:
        200:
          description: successful operation
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
        404:
          description: ""
          content: {}
    post:
      tags:
        - Aggregator
      parameters:
        - name: client_id
          in: path
          description: ID of the client
          required: true
          schema:
            type: string
        - name: client_token
          in: path
          description: Aggregator token of the client
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/octet-stream:
            schema:
              type: string
              format: binary
      responses:
        200:
          description: successful operation
          content: {}
        404:
          description: ""
          content: {}
components: {}
