openapi: 3.0.1
info:
  title: XAIN FL Coordinator API
  description: PET version
  contact:
    email: engineering@xain.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 0.8.0
externalDocs:
  description: Find out more about XAIN FL
  url: https://docs.xain.io/
servers:
  - url: http://localhost:8081/
paths:
  /round:
    get:
      description: PET Step 1, 2 (publish coord_pk, sum, update, seed)
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  coord_pk:
                    description: The public key of the coordinator.
                    type: string
                  sum:
                    description: The sum threshold of the current round.
                    type: string
                  update:
                    description: The update threshold of the current round.
                    type: string
                  seed:
                    description: The seed of the current round.
                    type: string
  /sum:
    post:
      description: PET Step 4 (receive "sum" message)
      requestBody:
        description: ""
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SumMessage"
      responses:
        200:
          description: OK
    get:
      description: PET Step 8 publish "sum" participants
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                additionalProperties:
                  type: string
                example:
                  part_pk_1: part_pk_fresh_1
                  part_pk_2: part_pk_fresh_2

  /update:
    post:
      description: PET Step 9 (receive "update" message)
      requestBody:
        description: ""
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateMessage"
      responses:
        200:
          description: OK
    get:
      description: PET Step 11 publish encrypted seeds
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                additionalProperties:
                  type: object
                  additionalProperties:
                    type: string
                example:
                  sum_encr_pk_1: { update_encr_pk_1: seed }
                  sum_encr_pk_2: { update_encr_pk_2: seed }
  /sum2:
    post:
      description: PET Step 12 (receive "update" message)
      requestBody:
        description: ""
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Sum2Message"
      responses:
        200:
          description: OK

components:
  schemas:
    SumMessage:
      description: Sum message
      type: object
      properties:
        message:
          description: ""
          type: string
          format: binary
        part_ephm_pk:
          description: ""
          type: string
          format: binary
        part_ephm_sk:
          description: ""
          type: string
          format: binary
    UpdateMessage:
      description: Update message
      type: object
      properties:
        message:
          description: ""
          type: string
          format: binary
        mask_seed:
          description: ""
          type: string
          format: binary
    Sum2Message:
      description: Sum2 message
      type: object
      properties:
        message:
          description: ""
          type: string
          format: binary
        mask_url:
          description: ""
          type: string
          format: url
