openapi: 3.0.1
info:
  title: XAIN FL Coordinator API
  description: PET version
  contact:
    email: engineering@xain.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 0.8.0
externalDocs:
  description: Find out more about XAIN FL
  url: https://docs.xain.io/
servers:
  - url: http://localhost:8081/
paths:
  /broadcast/round:
    get:
      description: PET Step 1, 2 (publish coord_pk, sum, update, seed)
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PublishRoundMessage"
  /participant/sum:
    post:
      description: PET Step 4 (send "sum" message)
      requestBody:
        description: ""
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SumMessage"
      responses:
        200:
          description: OK
        400:
          description: PET Error
  /broadcast/sum:
    get:
      description: PET Step 8 publish "sum" participants
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PublishSumParticipantsMessage"
        400:
          description: PET Error
  /participant/update:
    post:
      description: PET Step 9 (send "update" message)
      requestBody:
        description: ""
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateMessage"
      responses:
        200:
          description: OK
        400:
          description: PET Error
  /broadcast/seeds/{encr_pk}:
    get:
      description: PET Step 11 publish encrypted seeds
      parameters:
        - name: encr_pk
          description: The public key for asymmetric encryption of the participant.
          in: path
          required: true
          schema:
            $ref: "#/components/schemas/PublicKey"
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PublishEncryptedSeedsMessage"
        400:
          description: PET Error
  /participant/sum2:
    post:
      description: PET Step 12 (send "update" message)
      requestBody:
        description: ""
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Sum2Message"
      responses:
        200:
          description: OK
        400:
          description: PET Error

components:
  schemas:
    PublicKey:
      description: A public key.
      type: string
      format: binary
    SumMessage:
      description: Sum message
      type: object
      properties:
        message:
          type: object
          properties:
            round_box:
              type: string
              format: binary
            sum_box:
              type: string
              format: binary
    UpdateMessage:
      description: Update message
      type: object
      properties:
        message:
          type: object
          properties:
            round_box:
              type: string
              format: binary
            update_box:
              type: string
              format: binary
        mask_seed:
          description: "The encrypted seed."
          type: string
          format: binary
    Sum2Message:
      description: Sum2 message
      type: object
      properties:
        message:
          type: object
          properties:
            round_box:
              type: string
              format: binary
            sum2_box:
              type: string
              format: binary
        mask_url:
          description: "The URL which points to the global mask. The aggregator can use this URL to fetch the global mask."
          type: string
          format: url
    PublishRoundMessage:
      type: object
      properties:
        coord_pk:
          $ref: "#/components/schemas/PublicKey"
        sum:
          description: The sum threshold of the current round.
          type: number
          format: float
        update:
          description: The update threshold of the current round.
          type: number
          format: float
        seed:
          description: The seed of the current round.
          type: string
          format: bytes
    PublishSumParticipantsMessage:
      type: object
      additionalProperties:
        type: string
        format: binary
        example:
          part_pk_1: part_pk_fresh_1
          part_pk_2: part_pk_fresh_2
    PublishEncryptedSeedsMessage:
      type: object
      properties:
        seeds:
          type: array
          items:
            type: string
            format: binary
