openapi: 3.0.1
info:
  title: XAIN FL Coordinator API
  description: ""
  contact:
    email: engineering@xain.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
externalDocs:
  description: Find out more about XAIN FL
  url: https://docs.xain.io/
servers:
  - url: http://localhost:8081/
tags:
  - name: Coordinator
    description: Coordinator API
paths:
  /rendez_vous:
    get:
      tags:
        - Coordinator
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RendezVousResponse"
        404:
          description: ""
          content: {}
  /heartbeat/{client_id}:
    get:
      tags:
        - Coordinator
      parameters:
        - name: client_id
          in: path
          description: ID of the client
          required: true
          schema:
            type: string
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HeartBeatResponse"
        404:
          description: Client unknown
          content: {}
  /start_training/{client_id}:
    get:
      tags:
        - Coordinator
      parameters:
        - name: client_id
          in: path
          description: ID of the client
          required: true
          schema:
            type: string
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StartTrainingResponse"
        404:
          description: ""
          content: {}
components:
  schemas:
    RendezVousResponse:
      type: object
      properties:
        id:
          type: string
          description: Client ID
          example: 1fa2f908-83e2-4f92-80e1-4baee0bf25a5
        ok:
          type: boolean
          description: ""
    HeartBeatResponse:
      type: object
      properties:
        round:
          minimum: 0
          type: integer
          description: Current round of the coordinator
          format: int32
        state:
          type: string
          description: Current coordinator state
          enum:
            - stand_by
            - finish
            - round
            - reject
    StartTrainingResponse:
      type: object
      properties:
        url:
          type: string
          description: The URL of the aggregator
          example: http://localhost:8082
        token:
          type: string
          description: Token for the aggregator service
          example: 2e8700a6-390d-411f-977b-9aa3bebc13e9
        ok:
          type: boolean
          description: ""
