openapi: 3.0.1
info:
  title: XAIN FL Coordinator API
  description: PET version
  contact:
    email: engineering@xain.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 0.8.0
externalDocs:
  description: Find out more about XAIN FL
  url: https://docs.xain.io/
servers:
  - url: http://localhost:8081/
paths:
  /broadcast/round:
    get:
      description: PET Step 1, 2 (publish coord_pk, sum, update, seed)
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PublishRoundMessage"
  /participant/sum:
    post:
      description: PET Step 4 (send "sum" message)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SumMessage"
      responses:
        200:
          description: OK
        400:
          description: PET Error
  /broadcast/sum:
    get:
      description: PET Step 8 publish "sum" participants
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PublishSumParticipantsMessage"
        400:
          description: PET Error
  /participant/update:
    post:
      description: PET Step 9 (send "update" message)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateMessage"
      responses:
        200:
          description: OK
        400:
          description: PET Error
  /broadcast/seeds/{encr_pk}:
    get:
      description: PET Step 11 publish encrypted seeds
      parameters:
        - name: encr_pk
          description: The public key for asymmetric encryption of the participant.
          in: path
          required: true
          schema:
            type: string
            format: byte
            minLength: 32
            maxLength: 32
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PublishEncryptedSeedsMessage"
        400:
          description: PET Error
  /participant/sum2:
    post:
      description: PET Step 12 (send "update" message)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Sum2Message"
      responses:
        200:
          description: OK
        400:
          description: PET Error
components:
  schemas:
    SumMessage:
      description: Sum message
      type: object
      required:
        - message
      properties:
        message:
          type: object
          required:
            - round_box
            - sum_box
          properties:
            round_box:
              type: string
              format: byte
            sum_box:
              type: string
              format: byte
    UpdateMessage:
      description: Update message
      type: object
      required:
        - message
        - mask_seed
      properties:
        message:
          type: object
          required:
            - round_box
            - update_box
          properties:
            round_box:
              type: string
              format: byte
            update_box:
              type: string
              format: byte
        mask_seed:
          description: "The encrypted seed."
          type: string
          format: byte
          minLength: 32
          maxLength: 32
    Sum2Message:
      description: Sum2 message
      type: object
      required:
        - message
        - mask_url
      properties:
        message:
          type: object
          required:
            - round_box
            - sum2_box
          properties:
            round_box:
              type: string
              format: byte
            sum2_box:
              type: string
              format: byte
        mask_url:
          description: The URL that points to the global mask. The aggregator can use this URL to fetch the global mask.
          type: string
          format: url
    PublishRoundMessage:
      type: object
      properties:
        coord_pk:
          description: The public key of the coordinator.
          type: string
          format: byte
          minLength: 32
          maxLength: 32
        sum:
          description: The sum threshold of the current round.
          type: number
          format: float
          minimum: 0
          maximum: 1
        update:
          description: The update threshold of the current round.
          type: number
          format: float
          minimum: 0
          maximum: 1
        seed:
          description: The seed of the current round.
          type: string
          format: byte
          minLength: 32
          maxLength: 32
        global_model_url:
          description: The URL that points to the global model. Participants can use this URL to fetch the global model. On the first round, the value of the URL will be null.
          type: string
          format: url
          nullable: true
    PublishSumParticipantsMessage:
      type: object
      additionalProperties:
        type: string
        format: byte
        example:
          part_pk_1: part_pk_fresh_1
          part_pk_2: part_pk_fresh_2
    PublishEncryptedSeedsMessage:
      type: object
      properties:
        seeds:
          type: array
          items:
            type: string
            format: byte
            minLength: 32
            maxLength: 32
