[package]
name = "xaynet-server"
version = "0.1.0"
authors = ["Xayn Engineering <engineering@xaynet.dev>"]
edition = "2018"
description = "The Xayn Network project is building a privacy layer for machine learning so that AI projects can meet compliance such as GDPR and CCPA. The approach relies on Federated Learning as enabling technology that allows production AI applications to be fully privacy compliant."
license-file = "../../LICENSE"
keywords = ["federated-learning", "fl", "ai", "machine-learning"]
repository = "https://github.com/xaynetwork/xaynet/"
homepage = "https://xaynet.dev/"

[dependencies]
futures = "0.3.5"
tokio = { version = "0.2.22", features = [
    "rt-core",
    "rt-threaded",
    "tcp",
    "time",
    "macros",
    "signal",
    "sync",
    "stream",
] }
derive_more = { version = "0.99.10", default-features = false, features = [
    "display",
    "from",
    "as_ref",
    "as_mut",
    "into",
    "index",
    "index_mut",
    "deref",
] }
rand = "0.7.3"
rand_chacha = "0.2.2"
serde = { version = "1.0.116", features = ["derive"] }
bytes = "0.5.6"
sodiumoxide = "0.2.6"
num = { version = "0.3.0", features = ["serde"] }
bincode = "1.3.1"
thiserror = "1.0.20"
anyhow = "1.0.32"
bitflags = "1.2.1"
warp = "0.2.5"
config = "0.10.1"
validator = { version = "0.11.0", features = ["derive"] }
structopt = "0.3.17"
paste = "1.0.1"
tower = "0.3.1"
tracing = "0.1.19"
tracing-futures = "0.2.4"
tracing-subscriber = "0.2.12"
uuid = { version = "0.8.1", features = ["v4"] }
rayon = "1.4.0"
async-trait = "0.1.40"
xaynet-macros = { path = "../xaynet-macros", version = "0.1.0" }
xaynet-core = { path = "../xaynet-core", version = "0.1.0" }
redis = { version = "0.17.0", default-features = false, features = ["connection-manager", "aio", "tokio-rt-core", "script"] }

# optional dependencies
influxdb = { version = "0.1.0", features = ["derive"], optional = true }
chrono = { version = "0.4.15", optional = true }

[dev-dependencies]
tower-test = "0.3.0"
tokio-test = "0.2.1"
# We can't run tarpaulin with the flag `--test-threads=1` because it can
# trigger a segfault
# https://github.com/xd009642/tarpaulin/issues/317
# A workaround is to use `serial_test`
serial_test = "0.5.0"
xaynet-client = { path = "../xaynet-client", version = "0.1.0" }

[[bin]]
name = "coordinator"
path = "src/bin/main.rs"

[features]
default = []
tls = ["warp/tls"]
metrics = ["influxdb", "chrono"]
