apiVersion: apps/v1
kind: Deployment
metadata:
  name: aggregator-deployment
spec:
  selector:
    matchLabels:
      app: aggregator
  replicas: 1
  template:
    metadata:
      labels:
        app: aggregator
    spec:
      containers:
        - name: aggregator
          image: aggregator
          command:
            - aggregator -c /bin/config.toml
          ports:
            - containerPort: 6666
              protocol: TCP
            - containerPort: 8082
              protocol: TCP