apiVersion: v1
kind: Service
metadata:
  name: aggregator-service
spec:
  type: ClusterIP
  ports:
    - port: 8082
      targetPort: 8082
      name: http-port
    - port: 6666
      targetPort: 6666
      name: rpc-port
  selector:
    app: aggregator
