version: "3.8"
services:
  coordinator:
    image: xaynetwork/xaynet:release
    build:
      context: ..
      dockerfile: docker/Dockerfile.release
    command: /app/coordinator -c /app/config.toml
    volumes:
      - ${PWD}/configs/docker-release.toml:/app/config.toml
    networks:
      - xaynet
    ports:
      - "8081:8081"

networks:
  xaynet:
