versioe: "3.8"
services:

  coordinator:
    image: xain/xain-fl:valgrind
    build:
      context: ..
      dockerfile: docker/Dockerfile
    depends_on:
      - influxdb
    command: valgrind --leak-check=full --show-leak-kinds=all --track-origins=yes /app/coordinator -c /app/config.toml
    volumes:
      - ${PWD}/../configs/docker-dev-coordinator.toml:/app/config.toml
    networks:
      - xain-fl
    ports:
      - "5555:5555"
      - "8081:8081"

  influxdb:
    image: influxdb:1.8
    hostname: influxdb
    container_name: influxdb
    environment:
      INFLUXDB_DB: metrics
      INFLUXDB_DATA_QUERY_LOG_ENABLED: 'false'
      INFLUXDB_HTTP_LOG_ENABLED: 'false'
    volumes:
      - influxdb-data:/var/lib/influxdb
    networks:
      - xain-fl
    expose:
      - "8086"

networks:
  xain-fl:
