apiVersion: apps/v1
kind: Deployment
metadata:
  name: aggregator-deployment
spec:
  template:
    spec:
      volumes:
      - name: config-volume
        configMap:
          name: config-toml
          items:
            - key: config-release-aggregator.toml
              path: config-release-aggregator.toml
      containers:
        - name: aggregator
          volumeMounts:
            - name: config-volume
              mountPath: /app/config-release-aggregator.toml
              subPath: config-release-aggregator.toml
