apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: development

images:
- name: aggregator
  newName: xain/xain-fl
  newTag: latest

configMapGenerator:
- files:
  - docker-release-aggregator.toml
  name: config-toml

patchesStrategicMerge:
- history-limit.yaml
- config-volume-mount.yaml
resources:
- ../base
