[workspace]
members = [
    "xaynet",
    # "xaynet-analytics",
    "xaynet-core",
    "xaynet-mobile",
    "xaynet-server",
    "xaynet-sdk",

    # internals
    "benches",
    "examples",
]

[workspace.metadata]
# minimum supported rust version
msrv = "1.51.0"
