[package]
name = "examples"
version = "0.0.0"
publish = false
edition = "2018"

[dev-dependencies]
xaynet-client = { path = "../xaynet-client" }
xaynet-core = { path = "../xaynet-core" }
tracing = "0.1.19"
structopt = "0.3.17"
tracing-subscriber = "0.2.12"
sodiumoxide = "0.2.6"
tokio = { version = "0.2.22", features = ["full"] }

[features]
default = []
tls = ["xaynet-client/tls"]

[[example]]
name = "test-drive-net"
path = "test-drive-net.rs"

[[example]]
name = "mobile-client"
path = "mobile-client.rs"
