apiVersion: apps/v1
kind: Deployment
metadata:
  name: coordinator-deployment
spec:
  selector:
    matchLabels:
      app: coordinator
  replicas: 1
  template:
    metadata:
      labels:
        app: coordinator
    spec:
      containers:
        - name: coordinator
          image: coordinator
          command: ["coordinator"]
          args: ["-c", "/app/config-release-coordinator.toml"]
          ports:
            - containerPort: 5555
              protocol: TCP
            - containerPort: 8081
              protocol: TCP
