apiVersion: apps/v1
kind: Deployment
metadata:
  name: coordinator-deployment
spec:
  selector:
    matchLabels:
      app: coordinator
  replicas: 1
  template:
    metadata:
      labels:
        app: coordinator
    spec:
      containers:
        - name: coordinator
          image: coordinator
          imagePullPolicy: Always
          env:
            - name: RUST_LOG
              value: "DEBUG"
          command: ["/app/coordinator"]
          args: ["-c", "/app/config.toml"]
          ports:
            - containerPort: 8081
              protocol: TCP
