apiVersion: v1
kind: Service
metadata:
  name: coordinator-service
spec:
  type: ClusterIP
  ports:
    - port: 8081
      targetPort: 8081
      name: http
    - port: 5555
      targetPort: 5555
      name: grpc
  selector:
    app: coordinator
