[log]
filter = "xaynet=debug,http=warn,info"

[api]
bind_address = "127.0.0.1:8081"
tls_certificate = "/app/ssl/tls.pem"
tls_key = "/app/ssl/tls.key"
# tls_client_auth = "/app/ssl/trust_anchor.pem"

[pet.sum]
prob = 0.5
count = { min = 1, max = 100 }
time = { min = 5, max = 3600 }

[pet.update]
prob = 0.9
count = { min = 3, max = 10000 }
time = { min = 10, max = 3600 }

[pet.sum2]
count = { min = 1, max = 100 }
time = { min = 5, max = 3600 }

[mask]
group_type = "Prime"
data_type = "F32"
bound_type = "B0"
model_type = "M3"

[model]
length = 4

[metrics.influxdb]
url = "http://127.0.0.1:8086"
db = "metrics"

[redis]
url = "redis://127.0.0.1/"

[s3]
access_key = "minio"
secret_access_key = "minio123"
region = ["minio", "http://localhost:9000"]

[restore]
enable = true

[trust_anchor.iota]
url = "https://nodes.devnet.iota.org:443"
network = "Devnet"
author_seed = "XAYN9IOTA9AUTHOR9SEED999"
author_state_pwd = "xaynet_iota_test_password"

[trust_anchor.iota.store]
url = "redis://127.0.0.1/"
