[log]
filter = "xain_fl=debug,http=warn,info"

[api]
bind_address = "127.0.0.1:8081"

[pet]
min_sum = 1
min_update = 3
sum = 0.5
update = 0.9
expected_participants = 10

[mask]
group_type = "Prime"
data_type = "F32"
bound_type = "B0"
model_type = "M3"
