[log]
filter = "xain_fl=debug,http=warn,info"

[api]
bind_address = "0.0.0.0:8081"

[pet]
min_sum_count = 1
min_update_count = 3
sum = 0.01
update = 0.1
expected_participants = 10

[mask]
group_type = "Prime"
data_type = "F32"
bound_type = "B0"
model_type = "M3"
