[log]
filter = "xain_fl=debug,info"

[api]
bind_address = "0.0.0.0:8081"

[pet]
min_sum = 5
min_update = 50
sum = 0.1
update = 0.1
expected_participants = 1000

[mask]
group_type = "Prime"
data_type = "F32"
bound_type = "B0"
model_type = "M3"
