[server]
# Address to listen on for incoming gRPC connections. By listening on
# 0.0.0.0, the coordinator will open a port reachable from the
# outside.
host = "0.0.0.0"
# Port to listen on for incoming gRPC connections
port = 50051

[server.grpc_options]
# More information about all available gRPC options can be found here:
# https://grpc.github.io/grpc/cpp/group__grpc__arg__keys.html#ga813f94f9ac3174571dd712c96cdbbdc1

# Maximum message length that the channel can receive. -1 means unlimited.
"grpc.max_receive_message_length" = -1
# Maximum message length that the channel can send. -1 means unlimited.
"grpc.max_send_message_length" = -1

[ai]
# Number of global rounds the model is going to be trained for. This
# must be a positive integer.
rounds = 2
# Number of local epochs per round
epochs = 1
# Minimum number of participants to be selected for a round.
min_participants = 1
# Fraction of total clients that participate in a training round. This
# must be a float between 0 and 1.
fraction_participants = 1.0

[storage]
# URL to the storage service to use
endpoint = "http://minio-dev:9000"
# Name of the bucket for storing the global model weights
global_weights_bucket = "xain-fl-aggregated-weights"
# Name of the bucket for retrieving the local model weights
local_weights_bucket = "xain-fl-participants-weights"
# AWS access key ID to use to authenticate to the storage service
access_key_id = "minio"
# AWS secret access to use to authenticate to the storage service
secret_access_key = "minio123"

[logging]
# The log level can be one of "notset", "debug", "info", "warning",
# "error" and "critical". It defaults to "info".
level = "info"


[metrics]
enable = true
# The hostname to connect to InfluxDB.
host = "influxdb"
