aggregator_url = "http://localhost:8082"

[logging]
filter = "info,xain_fl=debug"
telemetry = { jaeger_endpoint = "jaeger:6831", service_name = "coordinator" }

[api]
bind_address = "0.0.0.0:8081"

[rpc]
bind_address = "0.0.0.0:5555"
aggregator_address = "aggregator:6666"

[federated_learning]
rounds = 100
participants_ratio = 0.8
min_clients = 100
heartbeat_timeout = 5

[metric_store]
database_url = "http://influxdb:8086"
database_name = "metrics"
