name: DockerHub (Release)

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  build-tag-push-release:
    name: build-tag-push-release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: build-tag-push
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: docker/Dockerfile.release
          cache_froms: buildpack-deps:stable-curl
          repository: xaynetwork/xaynet
          tag_with_ref: true
          push: true
