name: DockerHub (Release)

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  build-tag-push-release:
    name: build-tag-push-release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: build-tag-push
        id: docker
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: docker/Dockerfile.release
          cache_froms: buildpack-deps:stable-curl
          repository: xaynetwork/xaynet
          tag_with_ref: true
          push: true

      - name: Notify on Slack
        uses: 8398a7/action-slack@v3
        if: always()
        with:
          status: custom
          fields: workflow,job,repo,ref
          custom_payload: |
            {
              username: 'GitHub Actions',
              icon_emoji: ':octocat:',
              attachments: [{
                color: '${{ steps.docker.outcome }}' === 'success' ? 'good' : '${{ steps.docker.outcome }}' === 'failure' ? 'danger' : 'warning',
                text: `${process.env.AS_WORKFLOW}\nRepository: :xaynet: ${process.env.AS_REPO}\nRef: ${process.env.AS_REF} :heavy_check_mark:`,
              }]
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}