name: DockerHub + Kubernetes (master/development)

on:
  push:
    branches:
      - master

jobs:
  build-tag-push-master:
    name: build-tag-push-master
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      
      - name: build-tag-push
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: docker/Dockerfile
          cache_froms: buildpack-deps:stable-curl
          repository: xaynetwork/xaynet
          tag_with_ref: true
          tags: development
          push: true

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Get DigitalOcean kubeconfig
        run: doctl kubernetes cluster kubeconfig save ${{ secrets.K8S_CLUSTER }}

      - name: Re-apply manifests
        run: kubectl apply -n development -k $GITHUB_WORKSPACE/k8s/coordinator/development --prune -l "app.kubernetes.io/part-of=xaynet"

      - name: Force deployment rollout
        run: kubectl rollout -n development restart deployment/coordinator-deployment

      - name: Check deployment status
        run: kubectl rollout -n development status deployment/coordinator-deployment

      - name: Clean-up stale ReplicaSets
        run: kubectl delete -n development replicasets $(kubectl get -n development replicasets | awk 'NR!=1 && ($2==0) {print $1}')
