name: docker-compose validation

on:
  push:
    paths:
      - 'docker/docker-compose*yml'

jobs:
  check-docker-compose:
    name: docker-compose validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Verify docker-compose
        working-directory: ./docker
        run: docker-compose -f docker-compose.yml config -q
