name: DockerHub (Master)

on:
  push:
    branches:
      - master

jobs:
  build-tag-push-master:
    name: build-tag-push-master
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      
      - name: build-tag-push
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: docker/Dockerfile
          cache_froms: buildpack-deps:stable-curl
          repository: xaynetwork/xaynet
          tag_with_ref: true
          tags: development
          push: true
