name: Kubernetes manifests validation

on:
  push:
    paths:
      - 'k8s/**'
    
jobs:
  k8s-kustomize-validation:
    name: Kubernetes manifests validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Verify Kubernetes manifests
        run: kubectl kustomize $GITHUB_WORKSPACE/k8s/coordinator/development > /dev/null # Print only errors, if any
