name: Build test package

on:
  push:
    branches:
      - release/v[0-9]+.[0-9]+.[0-9]+

jobs:
  build_test_package:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.6

      - name: Cache pip packages
        uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: pip-master-${{ hashFiles('setup.py') }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade setuptools
          pip install wheel twine

      - name: Create packages
        run: |
          python setup.py sdist bdist_wheel

      - name: Output tag name
        id: get_tag_name
        run: echo ::set-output name=TAG_NAME::${GITHUB_REF##*/}

      - name: Upload packages
        uses: actions/upload-artifact@v1
        with:
          name: ${{ steps.get_tag_name.outputs.TAG_NAME }}-test
          path: dist
